---
- hosts: all
  gather_facts: yes

  vars:
    APP_PATH: /var/apps/hiveempire-smell
    NODE_VERSION: 5.6.0

  tasks:
    - name: Install Network Manager
      apt: name=network-manager state=present update_cache=yes
      sudo: yes
      tags:
        - network-install

    - name: Install node 1
      get_url: url=https://deb.nodesource.com/setup_4.x dest=~/ mode=0755
      sudo: yes
      tags:
        - node-install

    - name: Install node 2
      shell: ~/setup_4.x;apt-get update
      sudo: yes
      tags:
        - node-install

    - name: Install node
      apt: name=nodejs state=present update_cache=yes
      sudo: yes
      tags:
        - node-install

    - name: Install n
      npm: name=n global=yes
      sudo: yes
      tags:
        - node-install

    - name: Install node
      shell: n {{ NODE_VERSION }}
      sudo: yes
      tags:
        - node-install

    - name: Creates directory
      file: path="{{ APP_PATH }}" state=directory owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}"
      sudo: yes
      tags:
        - app-install

    - name: Copy packages
      copy: src="../{{ item }}" dest="{{ APP_PATH }}" owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}"
      with_items:
         - scanner.js
         - sniff.js
         - sneeze.js
         - package.json
         - config
         - sensor_events_db.schema
      sudo: yes
      tags:
        - app-install

    - name: Setup the database
      shell: sqlite3 {{ APP_PATH }}/sensor_events.db < {{ APP_PATH }}/sensor_events_db.schema
      tags:
        - app-db-install

    - name: Install packages
      npm: path="{{ APP_PATH }}" global=no
      tags:
        - app-packages-install

    - name: Setup the cron
      cron: name="HiveEmpire Sense" minute="0,15,30,45" job="NODE_ENV=production /usr/local/bin/node {{ APP_PATH }}/scanner.js > /dev/null"
      tags:
        - app-cron-install